# Generated by Django 4.2.16 on 2024-10-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cniapp', '0004_alter_comment_options_alter_review_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.CharField(blank=True, max_length=100)),
                ('overview', models.TextField(blank=True)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
