# Generated by Django 4.2.16 on 2024-11-01 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cniapp', '0007_review_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'managed': False, 'ordering': ['-created_on']},
        ),
    ]
