# Generated by Django 4.2.16 on 2024-11-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cniapp', '0008_alter_review_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'managed': True, 'ordering': ['-tomatometer_rating']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'managed': True, 'ordering': ['-created_on']},
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
